language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies
before_install:
  - python -m pip install --upgrade pip
install:
  - pip install -r requirements.txt
  - pip install .
# command to run tests
script:
  - pytest

notifications:
  email:
    on_success: never
    on_failure: always
